### ISSUE TITLE
As an administrator I want to login so I have full read/write access to all of the PZ tiles.

### ISSUE THREAD

**Issue by kfindley7** [kfindley7/JuniorDesign#1]
**Story/Task Details**

- Connect to MongoDB cluster 

- query DB for valid users to verify user input

- alert if user enters incorrect information

**Acceptance Scenarios**

Scenario: An administrator wants to login to the application
Given an administrator is on the login page;
When the administrator enters their username and password and presses the login button;
Then the administrator is directed to the home page.

Scenario: An administrator wants to login to the application but enters an invalid username or password.
Given an administrator is on the login page;
When the administrator enters an invalid username or password and clicks the ‘login’ button;
Then an error message is displayed that the username or password was incorrect.

**DONE DONE CRITERIA**

When user attempts to login, DB is queried to check user input and user is logged in (directed to home page) if input is in DB. Alerts are shown when the user enters incorrect input or tries to login without entering anything. Alert messages are clear and concise.

**Comment by whornsby** [comment]
All Done Done criteria implemented correctly
