### ISSUE TITLE
Selecting a tile on the map

### ISSUE THREAD

**Issue by kfindley7** [kfindley7/JuniorDesign#10]
## **Task Details**

- when page is loaded, need availability of tiles pertaining to planet selection 
- when a tile is selected, need to make sure that tile is valid for adding or removal
- when page is loaded color code tiles to show their availability: FREE (white), Not Available (Greyed out/black), Tiles in game (blue)
- when free tile is clicked turn it green, when current game tile is clicked turn it red
- when a valid tile is clicked, add to respective remove/add lists
    - lists are in a format of a list of JSON objects (planet, planet_id, tile_id, game)
- when user clicks save changes, pass those lists to respective methods in index
- show message to user if it was successful or there was an error

## **DONE DONE CRITERIA**

User clicks on tile: if tile is in game already, add to 'Removed Tiles' list, if tile is free add to 'Added Tiles' list. If a user clicks on a selected tile, unselect it and remove from the corresponding list. When user selects a tile, the coordinates of the tile that was clicked is mapped to a tile object that has been retrieved from the database. When user selects tile it is obvious to the user it is selected.

**Comment by whornsby** [comment]
This is just being held up by "Make a map view of the tiles from the database". Once that gets done it shouldn't be too hard to get the other features implemented
