### ISSUE TITLE
Make a map view of the tiles from the database

### ISSUE THREAD

**Issue by kfindley7** [kfindley7/JuniorDesign#12]
## **Task Details**

- When reservation page is loaded, default to planet earth at first. Query the database for all the tiles of the Prototype and their statuses and show them in map-view.

## **DONE DONE CRITERIA**

User is on reservation page. Prototype is shown by default with proper coloring. Tiles belonging to other games besides the specified game should be disabled (not clickable)/greyed out or another way to signify it is unavailable. Specify tiles that are already in the game or are free so user knows what they are clicking on (colored outline or something). Should have a dropdown on the page to switch views to other viewpoints of the park (other planets etc.). 'Save Changes' button should be across the bottom of the page

**Comment by whornsby** [comment]
I think all of the front end for this is done until we can get the information from the database

**Comment by kfindley7** [comment]
Yes I agree
