### ISSUE TITLE
Refactor CSS files of login page, recover password, register pages

### ISSUE THREAD

**Issue by kfindley7** [kfindley7/JuniorDesign#15]
## **Task Details**

- The css files are horrendous right now. Html pages are using duplicate stylings so create or add to common.css with all the navigation header stuff (back, logout, edit task, visualization buttons etc).

- Anywhere that 2 or more pages use same stylings for same html features, put in common.css. Otherwise put in specific css pages for that specific page.

- put any inline styling in html into css pages

- this only involves the pages listed in header to keep this task manageable

- I recommend renaming some CSS classes to make more generic. Also be careful that some javascript files use the class names to reference the html components so make sure you change those names as well. SUPER IMPORTANT

## **DONE DONE CRITERIA**

This could affect a lot of behavior and layout of the app so anything you change please make sure that the functionality is not changed in any way. Do things in small steps. Start with one page at a time and **TEST FREQUENTLY**. Add any duplicate styling among pages into a common.css file, otherwise keep in page specific css pages. Make sure html page includes the new css pages. 
When all functionality is preserved and css files have been properly organized, then this task is done

**Comment by mtmarcus** [comment]
Will tackle this today/tonight
