### ISSUE TITLE
Change add/remove confirmation dialogs to one

### ISSUE THREAD

**Issue by kfindley7** [kfindley7/JuniorDesign#19]
## **Task Details**

- currently when a user adds/removes tiles and clicks 'save changes' they are shown 2 separate dialogs to say the add and remove process was successful. Convert to one dialog.

- use flags to specify if there were just removals, additions, or both and show on one dialog for success or failures

## **DONE DONE CRITERIA**

When a user clicks save changes they are only shown one dialog with either successful output or what went wrong.

**Comment by whornsby** [comment]
Are there supposed to be separate alerts for just adding tiles and just removing tiles, or is everything supposed to say added/removed even if only one of those things was done?

**Comment by kfindley7** [comment]
I wasn't sure which one we wanted to do so I just had one that said both because it was a bit easier.

**Comment by whornsby** [comment]
K. Works as intended then.
