### ISSUE TITLE
As a user I want to be able to recover my password.

### ISSUE THREAD

**Issue by kfindley7** [kfindley7/JuniorDesign#2]
## **Story/Task Details**

- Have user enter their username and their answers to the two security questions

- Check if all info is in the DB and send to reset password page if valid

- otherwise give error message

 ## **Acceptance Scenarios**

Scenario: An administrator wants to login but has forgotten their password.
Given the administrator is on the login page.
When the administrator clicks on the ‘Forgot Password’ link;
Then the administrator is directed to the ‘Forgot Password’ page.
When the administrator enters their correct username and answers to security questions associated with their account and clicks the ‘Send Request’ button on the bottom;
Then the administrator is directed to the 'Reset Password' page.
When the admin enters a new password and clicks on the submit button.
Then the new password is saved and the admin is directed to the login page.

Scenario: An administrator wants to login but has clicked the ‘Forgot Password’ link by mistake.
Given the administrator is on the ‘Forgot Password’ page.
When the administrator clicks the ‘Back’ button;
Then the administrator will be directed back to the login page. 

## **DONE DONE CRITERIA**

User enters a valid username and answers to their security questions, they are directed to reset password page. If they enter any or all incorrect information, an error message is shown. On the reset password page, make sure the user enters the same password in both boxes (new and confirm password boxes). On clicking the submit button either the new password is saved or proper error messages are shown.

**Comment by whornsby** [comment]
Only things left to do are create a page to input a new password and get the backend to update the database.

**Comment by kfindley7** [comment]
Functionality works great. Only thing is that the text on the forgot password button doesn't fit in the actual button

**Comment by kfindley7** [comment]
Looks good! Merge is complete
