### ISSUE TITLE
Refactor main.js

### ISSUE THREAD

**Issue by whornsby** [kfindley7/JuniorDesign#21]
## **Task Details**

-Right now code for the login page and for the main page are in the same file, but these should be split up for easier maintenence in the future and for better design in general.

- create new file login.js that will hold all the code for login and leave main page code unaffected in main.js

- change the html pages to only include their respective js files

## **DONE DONE CRITERIA**

Both pages still work after all code has been isolated to the correct js file.

**Comment by whornsby** [comment]
Changes made on refactor_js branch

**Comment by kfindley7** [comment]
Everything seems to be working just fine. Looks so much better. Good job

**Comment by kfindley7** [comment]
Merge completed
