### ISSUE TITLE
Add backend support for modifying tile mappings

### ISSUE THREAD

**Issue by kfindley7** [kfindley7/JuniorDesign#23]
## **Story/Task Details**
- Add database methods in index.js to take in a list of json tile objects and update the database accordingly.  Should be similar to tile reservation methods. Input will be list of changes where each item in the list is a json object with the planet, planet_id, and new mapping setting. This should be enough info to update the database.
- tile info is formatted as follows: [{ planet: "", planet_id: "", mapping: ""}] - list of tile objects

## **DONE DONE CRITERIA**

When the 'Save Changes' button is clicked, database will be updated and if successful, send back success message for front end pop-up, if unsuccessful, return list of failed tiles.

**Comment by jberry91** [comment]
Can be tested once the front end is completed.
