### ISSUE TITLE
Modify CSS to address UI improvements

### ISSUE THREAD

**Issue by mtmarcus** [kfindley7/JuniorDesign#25]
In order to move towards the final presentation, a set of stories beginning with this one will start to address visuals on the application to make sure that the users a "delighted" as they use the application.

This specific story begins this general epic.

**Comment by mtmarcus** [comment]
- Home page w/navigation

**Comment by mtmarcus** [comment]
<img width="1071" alt="screen shot 2017-10-30 at 4 52 12 pm" src="https://user-images.githubusercontent.com/2137913/32195113-be7858aa-bd92-11e7-816c-6a2dc1373b3a.png">

Here is an example of a top bar

**Comment by kfindley7** [comment]
I finished some stuff early so I changed the nav bar. I will go ahead and push to branch for edit tile mappings since it was just html changes (shouldn't conflict badly). Let me know what you guys think

I used this as a reference: https://www.w3schools.com/css/css_navbar.asp

**Comment by kfindley7** [comment]
Created new nav bar, fixed CSS styling to be compatible across Chrome, Firefox, and Safari, along with other CSS styling changes to make UI look cleaner. Changes are in mapping_backend branch.

**Comment by kfindley7** [comment]
We should probably change the register stuff to an actual html form instead of just a lot of input elements

**Comment by kfindley7** [comment]
@mtmarcus On the recover password page, the back button spans most of the screen and covers up the recover password title
