### ISSUE TITLE
View home page with currently running games

### ISSUE THREAD

**Issue by kfindley7** [kfindley7/JuniorDesign#4]
## **Task Details**

- When home page is loaded, query database to get the distinct games that are currently running and show them in a list form in the home page

- Format page correctly with logout button in top right, title in top left, task buttons below them in a row (Edit Task, Visualization, Sensing)

## **DONE DONE CRITERIA**

However a user gets to the page, the home page needs to be populated with the most recent games in a list. Formatting is correct (refer to second bullet point above). Querying database by using a socket.io call to index.js from main.js and then transferred to html dynamically.

**Comment by whornsby** [comment]
Edit Task and Sensing tabs don't link to anything, but everything else is done.

**Comment by kfindley7** [comment]
We can add links to those buttons when those pages are created
