### ISSUE TITLE
Logout from the home page

### ISSUE THREAD

**Issue by kfindley7** [kfindley7/JuniorDesign#5]
## **Task Details**

- Add functionality to logout button on home page so when user clicks it, they are directed to login page

## **Acceptance Scenarios**

Scenario: A user wants to logout of the application.
Given the user is on the home page.
When the user clicks on the logout button;
Then a confirmation popup window will appear.
When they click yes on the popup.
Then they are logged out of the application and directed to the login page.

Scenario: A user changes their mind about logging out.
Given the user is on the home page and has clicked the logout button.
When the user click no on the confirmation popup.
Then they are directed back to the home page and not logged out of the application.

## **DONE DONE CRITERIA**

- logout button brings up a confirmation popup asking if they are sure they want to logout. If a user clicks yes then direct to login page, if no go back to the page they were on.

**Comment by whornsby** [comment]
No logout confirmation alert when on Visualization or Create New Activity Page

**Comment by kfindley7** [comment]
Added logout functionality to create activity and visualization pages
